services:
  - type: web
    name: coaching-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn coaching_system.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: coaching_system.settings
